# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 The Allwinner BSP DDK Project

load("//build/kernel/kleaf:kernel.bzl", "ddk_module", "ddk_headers")
load("//devices/allwinner:rules.bzl", "ddk_install")

ddk_module(
    name = "aic8800_btlpm",
    srcs = [
        "aic8800_btlpm.c",
    ],
    out = "aic8800_btlpm.ko",
    defconfig = "//devices/allwinner:allwinner_defconfig.fragment",
    kernel_build = "//devices/allwinner:allwinner_android",
    deps = [
        "//devices/allwinner/bsp:allwinner_bsp_headers",
    ],
    visibility = ["//devices/allwinner:__subpackages__"],
)

ddk_install(
    name = "aic8800_btlpm_install",
    ddk_module = ":aic8800_btlpm",
)
