# SPDX-License-Identifier: GPL-2.0-only
obj-y += cpufreq-linux-$(VERSION).$(PATCHLEVEL)/
obj-$(CONFIG_ARM_AW_SUN50I_CPUFREQ_NVMEM) += sun50i-cpufreq-nvmem.o
obj-$(CONFIG_AW_CPUFREQ_TEST) += vf-test.o
ccflags-y := -DDYNAMIC_DEBUG_MODULE