# SPDX-License-Identifier: GPL-2.0
ccflag-y += -DDYNAMIC_DEBUG_MODULE

ccflags-y += -I $(srctree)/drivers/pci/
ccflags-y += -I $(srctree)/drivers/pci/controller/dwc/

obj-$(CONFIG_PCIE_DW_SUNXI_HOST) += pcie-dw-sunxi.o
